import type { Service, Stylist, GalleryItem, Testimonial, FAQItem } from "@/types";

export const services: Service[] = [
  {
    id: "womens-haircut",
    name: "Women's Haircut",
    description: "A precision cut tailored to your face shape, hair texture, and lifestyle. Includes consultation, wash, and blow-dry.",
    duration: 60,
    price: 85,
    category: "Cuts",
    image: "https://images.unsplash.com/photo-1560869713-7d0a29430803?w=800&q=80",
    featured: true,
    active: true,
    createdAt: "2024-01-01",
  },
  {
    id: "mens-haircut",
    name: "Men's Haircut",
    description: "Sharp, modern cuts crafted with clipper and scissor techniques. Includes wash, cut, and style.",
    duration: 45,
    price: 55,
    category: "Cuts",
    image: "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=800&q=80",
    featured: true,
    active: true,
    createdAt: "2024-01-01",
  },
  {
    id: "blowout",
    name: "Blowout & Styling",
    description: "Professional blow-dry and styling for any occasion. Choose from sleek, voluminous, or textured finishes.",
    duration: 45,
    price: 65,
    category: "Styling",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
    featured: false,
    active: true,
    createdAt: "2024-01-01",
  },
  {
    id: "balayage",
    name: "Balayage",
    description: "Hand-painted highlights for a sun-kissed, dimensional look. Customized to complement your skin tone and style.",
    duration: 150,
    price: 200,
    category: "Color",
    image: "https://images.unsplash.com/photo-1562322140-8baeececf3df?w=800&q=80",
    featured: true,
    active: true,
    createdAt: "2024-01-01",
  },
  {
    id: "full-highlights",
    name: "Full Highlights",
    description: "Comprehensive foiling technique for full-head brightness and dimension. Includes toner and gloss finish.",
    duration: 120,
    price: 180,
    category: "Color",
    image: "https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=800&q=80",
    featured: false,
    active: true,
    createdAt: "2024-01-01",
  },
  {
    id: "single-process",
    name: "Single Process Color",
    description: "All-over permanent or demi-permanent color for vibrant, long-lasting results. Gray coverage available.",
    duration: 60,
    price: 95,
    category: "Color",
    image: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80",
    featured: false,
    active: true,
    createdAt: "2024-01-01",
  },
  {
    id: "keratin-treatment",
    name: "Keratin Treatment",
    description: "Smoothing treatment that eliminates frizz and adds incredible shine. Results last up to 3 months.",
    duration: 90,
    price: 150,
    category: "Treatments",
    image: "https://images.unsplash.com/photo-1717160675489-7779f2c91999?w=800&q=80",
    featured: true,
    active: true,
    createdAt: "2024-01-01",
  },
  {
    id: "scalp-treatment",
    name: "Scalp Treatment",
    description: "Therapeutic scalp care addressing dryness, oiliness, or sensitivity. Includes massage and customized serum.",
    duration: 45,
    price: 75,
    category: "Treatments",
    image: "https://images.unsplash.com/photo-1563241527-3004b7be0ffd?w=800&q=80",
    featured: false,
    active: true,
    createdAt: "2024-01-01",
  },
  {
    id: "deep-conditioning",
    name: "Deep Conditioning",
    description: "Intensive moisture treatment that restores vitality and softness to dry or damaged hair.",
    duration: 30,
    price: 55,
    category: "Treatments",
    image: "https://images.unsplash.com/photo-1519735777090-ec97162dc266?w=800&q=80",
    featured: false,
    active: true,
    createdAt: "2024-01-01",
  },
  {
    id: "updo",
    name: "Updo / Special Occasion",
    description: "Elegant updos for weddings, galas, or any special event. Consultation and trial included.",
    duration: 60,
    price: 120,
    category: "Styling",
    image: "https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=800&q=80",
    featured: false,
    active: true,
    createdAt: "2024-01-01",
  },
  {
    id: "bridal-package",
    name: "Bridal Package",
    description: "Comprehensive bridal hair service including consultation, trial, and day-of styling. Travel fee may apply.",
    duration: 180,
    price: 350,
    category: "Styling",
    image: "https://images.unsplash.com/photo-1510076857177-7470076d4098?w=800&q=80",
    featured: true,
    active: true,
    createdAt: "2024-01-01",
  },
  {
    id: "gloss-toner",
    name: "Gloss / Toner",
    description: "Refresh your color between services with a gloss or toner that adds shine and corrects unwanted tones.",
    duration: 30,
    price: 55,
    category: "Color",
    image: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80",
    featured: false,
    active: true,
    createdAt: "2024-01-01",
  },
];

export const stylists: Stylist[] = [
  {
    id: "isabella-rossi",
    name: "Isabella Rossi",
    title: "Master Stylist & Founder",
    bio: "With over a decade of experience, Isabella founded Luxe Hair Studio to create a sanctuary where artistry meets hospitality. Trained in Milan and New York, she brings editorial precision to every client.",
    specialties: ["Balayage", "Precision Cuts", "Editorial Styling", "Transformations"],
    experience: 12,
    image: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=800&q=80",
    instagram: "https://instagram.com/isabellarossihair",
    active: true,
    createdAt: "2024-01-01",
  },
  {
    id: "marcus-chen",
    name: "Marcus Chen",
    title: "Color Specialist",
    bio: "Marcus is a colour virtuoso whose work has graced editorial pages across North America. His deep understanding of colour theory allows him to create bespoke shades that flatter every complexion.",
    specialties: ["Creative Color", "Balayage", "Color Correction", "Foil Techniques"],
    experience: 8,
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
    instagram: "https://instagram.com/marcuschencolor",
    active: true,
    createdAt: "2024-01-01",
  },
  {
    id: "amara-okafo",
    name: "Amara Okafor",
    title: "Precision Cutter",
    bio: "Amara's architectural approach to cutting has earned her a devoted following. She specialises in textured cuts, curly hair, and tailoring shapes that grow out beautifully.",
    specialties: ["Curly Hair", "Textured Cuts", "Razor Cutting", "Short Styles"],
    experience: 6,
    image: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=800&q=80",
    instagram: "https://instagram.com/amaraokafohair",
    active: true,
    createdAt: "2024-01-01",
  },
  {
    id: "james-bennett",
    name: "James Bennett",
    title: "Extension Specialist",
    bio: "James is a certified extension expert specialising in tape-in, sew-in, and micro-link methods. He believes great extensions should look and feel completely natural.",
    specialties: ["Hair Extensions", "Tape-In", "Micro-Link", "Custom Blending"],
    experience: 10,
    image: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=800&q=80",
    instagram: "https://instagram.com/jamesbennetthair",
    active: true,
    createdAt: "2024-01-01",
  },
  {
    id: "sofia-reyes",
    name: "Sofia Reyes",
    title: "Curl Specialist",
    bio: "Sofia is passionate about celebrating natural texture. Trained in the DevaCurl and Ouidad methods, she helps clients embrace and enhance their curls with custom techniques.",
    specialties: ["Curly Hair", "DevaCurl", "Ouidad", "Curl Coaching"],
    experience: 7,
    image: "https://images.unsplash.com/photo-1580489944761-15a19d654956?w=800&q=80",
    instagram: "https://instagram.com/sofiareyescurls",
    active: true,
    createdAt: "2024-01-01",
  },
  {
    id: "liam-walsh",
    name: "Liam Walsh",
    title: "Men's Grooming Expert",
    bio: "Liam brings barbershop precision to the salon floor. From classic tapers to modern textured crops, he delivers clean, sharp looks tailored to each client's style.",
    specialties: ["Men's Cuts", "Beard Grooming", "Hot Towel Shaves", "Clipper Work"],
    experience: 5,
    image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&q=80",
    instagram: "https://instagram.com/liamwalshgrooming",
    active: true,
    createdAt: "2024-01-01",
  },
];

export const galleryItems: GalleryItem[] = [
  { id: "g1", src: "https://images.unsplash.com/photo-1562322140-8baeececf3df?w=800&q=80", alt: "Balayage transformation", category: "Color", stylist: "Isabella Rossi", createdAt: "2024-06-01" },
  { id: "g2", src: "https://images.unsplash.com/photo-1560869713-7d0a29430803?w=800&q=80", alt: "Blunt bob haircut", category: "Cuts", stylist: "Amara Okafor", createdAt: "2024-06-02" },
  { id: "g3", src: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80", alt: "Bridal updo", category: "Bridal", stylist: "Isabella Rossi", createdAt: "2024-06-03" },
  { id: "g4", src: "https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=800&q=80", alt: "Full highlight and toner", category: "Color", stylist: "Marcus Chen", createdAt: "2024-06-04" },
  { id: "g5", src: "https://images.unsplash.com/photo-1599351431202-1e0f0137899a?w=800&q=80", alt: "Classic men's cut", category: "Cuts", stylist: "Liam Walsh", createdAt: "2024-06-05" },
  { id: "g6", src: "https://images.unsplash.com/photo-1510076857177-7470076d4098?w=800&q=80", alt: "Bridal party styling", category: "Bridal", stylist: "Isabella Rossi", createdAt: "2024-06-06" },
  { id: "g7", src: "https://images.unsplash.com/photo-1717160675489-7779f2c91999?w=800&q=80", alt: "Keratin smoothing treatment", category: "Treatments", stylist: "Sofia Reyes", createdAt: "2024-06-07" },
  { id: "g8", src: "https://images.unsplash.com/photo-1563241527-3004b7be0ffd?w=800&q=80", alt: "Scalp treatment session", category: "Treatments", stylist: "James Bennett", createdAt: "2024-06-08" },
  { id: "g9", src: "https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&q=80", alt: "Salon glam blowout", category: "Styling", stylist: "Sofia Reyes", createdAt: "2024-06-09" },
  { id: "g10", src: "https://images.unsplash.com/photo-1595476108010-b4d1f102b1b1?w=800&q=80", alt: "Elegant updo", category: "Styling", stylist: "Isabella Rossi", createdAt: "2024-06-10" },
  { id: "g11", src: "https://images.unsplash.com/photo-1519735777090-ec97162dc266?w=800&q=80", alt: "Deep conditioning treatment", category: "Treatments", stylist: "Sofia Reyes", createdAt: "2024-06-11" },
  { id: "g12", src: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?w=800&q=80", alt: "Master stylist at work", category: "Styling", stylist: "Isabella Rossi", createdAt: "2024-06-12" },
  { id: "g13", src: "https://images.unsplash.com/photo-1717160675489-7779f2c91999?w=800&q=80", alt: "Color consultation", category: "Color", stylist: "Marcus Chen", createdAt: "2024-06-13" },
  { id: "g14", src: "https://images.unsplash.com/photo-1562322140-8baeececf3df?w=800&q=80", alt: "Beach wave styling", category: "Styling", stylist: "Amara Okafor", createdAt: "2024-06-14" },
  { id: "g15", src: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&q=80", alt: "Wedding hairstyle", category: "Bridal", stylist: "Isabella Rossi", createdAt: "2024-06-15" },
  { id: "g16", src: "https://images.unsplash.com/photo-1605497788044-5a32c7078486?w=800&q=80", alt: "Vivid color transformation", category: "Color", stylist: "Marcus Chen", createdAt: "2024-06-16" },
];

export const testimonials: Testimonial[] = [
  {
    id: "t1",
    name: "Sarah Mitchell",
    rating: 5,
    content: "Absolutely incredible experience. Isabella transformed my hair beyond what I thought possible. The balayage is stunning and the salon atmosphere is pure luxury. I've never felt more pampered.",
    featured: true,
    createdAt: "2024-11-15",
  },
  {
    id: "t2",
    name: "David Chen",
    rating: 5,
    content: "Liam gives the best men's haircut I've ever had. Clean, precise, and the hot towel shave is a ritual I look forward to every month. Worth every penny.",
    featured: true,
    createdAt: "2024-11-10",
  },
  {
    id: "t3",
    name: "Priya Sharma",
    role: "Regular Client",
    rating: 5,
    content: "I've been coming to Luxe for two years and Marcus is a true colour genius. My blonde has never looked more natural. The team is warm and professional.",
    featured: true,
    createdAt: "2024-11-05",
  },
  {
    id: "t4",
    name: "Emma Thompson",
    rating: 4,
    content: "Amara is fantastic with curly hair. She listened to what I wanted and delivered a cut that finally works with my texture. The styling advice was invaluable.",
    featured: false,
    createdAt: "2024-10-28",
  },
  {
    id: "t5",
    name: "James Wilson",
    rating: 5,
    content: "My fiancée booked a bridal consultation and trial. Isabella made her feel like a queen. The bridal package is expensive but the results were absolutely worth it.",
    featured: false,
    createdAt: "2024-10-20",
  },
  {
    id: "t6",
    name: "Olivia Garcia",
    rating: 5,
    content: "I was nervous about extensions but James put me completely at ease. The tape-ins are seamless and feel so natural. My hair has never been this full and healthy-looking.",
    featured: true,
    createdAt: "2024-10-15",
  },
  {
    id: "t7",
    name: "Maya Patel",
    rating: 4,
    content: "The keratin treatment changed my life. My frizz is gone and my hair is silky smooth. Sofia was knowledgeable and made sure I understood how to maintain it.",
    featured: false,
    createdAt: "2024-10-08",
  },
  {
    id: "t8",
    name: "Ryan O'Brien",
    rating: 5,
    content: "Best salon experience in the city. From the espresso on arrival to the meticulous cut, every detail is considered. The atmosphere is peaceful and sophisticated.",
    featured: false,
    createdAt: "2024-10-01",
  },
  {
    id: "t9",
    name: "Charlotte Brooks",
    rating: 5,
    content: "I've struggled with scalp sensitivity for years. The scalp treatment at Luxe was transformative — soothing, effective, and the massage alone is worth the visit.",
    featured: false,
    createdAt: "2024-09-25",
  },
  {
    id: "t10",
    name: "Aisha Mohammed",
    rating: 4,
    content: "The blowout service is my weekly indulgence. My stylist always nails the volume and smoothness. The products they use smell divine and my hair stays perfect for days.",
    featured: false,
    createdAt: "2024-09-18",
  },
  {
    id: "t11",
    name: "Nathan Keller",
    rating: 5,
    content: "Came in for a complete style overhaul. Marcus and Isabella consulted together and created a look that's modern, professional, and totally me. Exceptional teamwork.",
    featured: false,
    createdAt: "2024-09-12",
  },
  {
    id: "t12",
    name: "Victoria Lane",
    rating: 5,
    content: "The attention to detail is unmatched. Every stylist here is an artist. My updo for my sister's wedding stayed perfect through 12 hours of dancing. Pure magic.",
    featured: false,
    createdAt: "2024-09-05",
  },
];

export const faqs: FAQItem[] = [
  {
    id: "f1",
    question: "Do I need to book an appointment, or do you accept walk-ins?",
    answer: "We strongly recommend booking an appointment to ensure availability, especially for colour services and weekends. However, we do accept walk-ins when space permits. You can book online or call us directly.",
    order: 1,
    active: true,
    createdAt: "2024-01-15",
  },
  {
    id: "f2",
    question: "What is your cancellation policy?",
    answer: "We require at least 24 hours' notice for cancellations or rescheduling. Late cancellations and no-shows are subject to a 50% service fee. We appreciate your understanding as this allows us to accommodate other clients.",
    order: 2,
    active: true,
    createdAt: "2024-01-15",
  },
  {
    id: "f3",
    question: "How much do services typically cost?",
    answer: "Pricing varies by stylist seniority and service complexity. Our cuts start at $55, colour services from $95, and treatments from $55. View our full pricing page for detailed information. We provide transparent pricing with no hidden fees.",
    order: 3,
    active: true,
    createdAt: "2024-01-15",
  },
  {
    id: "f4",
    question: "Do you offer consultations before colour services?",
    answer: "Absolutely. We recommend booking a consultation for any major colour change, correction, or first-time balayage. Consultations are complimentary and allow us to assess your hair, discuss your goals, and provide a tailored recommendation.",
    order: 4,
    active: true,
    createdAt: "2024-01-15",
  },
  {
    id: "f5",
    question: "What products do you use and sell?",
    answer: "We exclusively use and carry Oribe, Olaplex, and Kérastase products — trusted industry leaders known for their exceptional quality. Our team will recommend the best products for your hair type and concerns. All products are available for purchase at the salon.",
    order: 5,
    active: true,
    createdAt: "2024-01-15",
  },
  {
    id: "f6",
    question: "How long does a typical appointment take?",
    answer: "A standard cut and style takes 45–60 minutes. Colour services range from 60 minutes (single process) to 2.5 hours (balayage or full highlights). Treatments add 30–90 minutes. We always provide an estimated timeframe when you book.",
    order: 6,
    active: true,
    createdAt: "2024-01-15",
  },
  {
    id: "f7",
    question: "Do you accommodate clients with allergies or sensitivities?",
    answer: "Yes. Please inform us when booking if you have any allergies, sensitivities, or scalp conditions. We carry hypoallergenic and sensitive-skin options, and our team is trained to perform patch tests when needed.",
    order: 7,
    active: true,
    createdAt: "2024-01-15",
  },
  {
    id: "f8",
    question: "What is your policy on children in the salon?",
    answer: "We welcome well-supervised children. For their safety and comfort, we ask that children remain seated with their parent or guardian at all times. We offer children's haircut services for ages 12 and under by appointment.",
    order: 8,
    active: true,
    createdAt: "2024-01-15",
  },
  {
    id: "f9",
    question: "Do you offer bridal or event trials?",
    answer: "Yes. Our bridal package includes a dedicated consultation and trial session to perfect your look before the big day. We recommend booking the trial 4–6 weeks in advance. Additional event styling is available upon request.",
    order: 9,
    active: true,
    createdAt: "2024-01-15",
  },
  {
    id: "f10",
    question: "Can I tip my stylist?",
    answer: "Gratuities are graciously accepted and appreciated. Industry standard is 15–20% of the service total. We also offer the option to add gratuity when paying by card. Our stylists are independent professionals, and tips are a meaningful way to recognise exceptional service.",
    order: 10,
    active: true,
    createdAt: "2024-01-15",
  },
  {
    id: "f11",
    question: "What payment methods do you accept?",
    answer: "We accept Visa, Mastercard, American Express, debit cards, and cash. We also offer digital payment via Apple Pay and Google Pay. Gift cards are available for purchase online and in the salon.",
    order: 11,
    active: true,
    createdAt: "2024-01-15",
  },
  {
    id: "f12",
    question: "Do you offer any loyalty programmes or membership options?",
    answer: "Yes. Our Luxe Rewards programme gives you points on every dollar spent, redeemable toward future services and products. Members also receive exclusive perks like birthday bonuses, early access to new services, and seasonal promotions.",
    order: 12,
    active: true,
    createdAt: "2024-01-15",
  },
];

export const categories = ["All", "Cuts", "Color", "Treatments", "Styling"];
export const galleryCategories = ["All", "Cuts", "Color", "Styling", "Bridal"];
